server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/**/*.log # 在promtail配置文件中添加了对指定路径日志的抓取，注意：这里抓取的是Docker容器实例内部的路径

# 如下是在Promtail中添加抓取应用系统日志的配置
- job_name: myapp                # 区分不同抓取配置的标识
  static_configs:
  - targets:
      - localhost                # 上报日志的Loki地址
    labels:
      job: myapp-log             # 具体的任务名称，将来在Grafana中查询日志时作为过滤标签使用
      __path__: /myapp/logs/*log # 需要抓取的日志路径
